# The URL the site will be built for
base_url = "https://blog.sradjoker.cc"

# The site title and description; used in feeds by default.
title = "Sravan's blog"
description = "NBA, Linux & Single Board Computers"
author = "Sravan"

# Theme
theme= "archie-zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{ name = "tags" }]

default_language = "en"

generate_feed = true

feed_filename = "atom.xml"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# highlight_theme = "OneHalfLight"
highlight_theme = "css"

highlight_themes_css = [
  { theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
  { theme = "gruvbox-light", filename = "syntax-theme-light.css" },
]

[extra]

# control dark mode: auto | dark | toggle
mode = "toggle"

subtitle = "Linux and Tech related stuff"

# interal CDN resource
useCDN = false

favicon = "/icon/favicon.png"

copyright = "Sravan"

keywords = "tech,linux,nba,analytics,datavisualization,stats"

banner = true

summary = true

# ga = "G-6YGDB8SLBT"

# math support
katex_enable = true
katex_auto_render = true

[extra.translations]
# languages = [{name = "en", url = "/"}]

[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "Home", url = "/", weight = 2 },
    { name = "NBA", url = "/tags/nba/", weight = 3 },
    { name = "Linux", url = "/tags/linux/", weight = 3 },
    { name = "All posts", url = "/posts", weight = 3 },
    { name = "Tags", url = "/tags/", weight = 3 },
    { name = "Now", url = "/now/", weight = 4 },
    { name = "Uses", url = "/uses/", weight = 4 },
    { name = "About", url = "/about/", weight = 5 },
]

# config social icon info in the footer
[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/SravanNBA"

[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/sravanpannala"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/sradjoker"
