# The URL the site will be built for
base_url = "https://blog.sradjoker.cc"

# The site title and description; used in feeds by default.
title = "sradjoker/SravanNBA's blog"
description = "NBA, Linux, Single Board Computers and Tech related stuff"

# Theme
theme= "archie-zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [{ name = "tags" }]

default_language = "en"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "OneHalfDark"
#highlight_theme = "css"

highlight_themes_css = [
  { theme = "OneHalfDark", filename = "syntax-theme-dark.css" },
  { theme = "OneHalfLight", filename = "syntax-theme-light.css" },
]

#@import url("syntax-theme-dark.css") (prefers-color-scheme: dark);
#@import url("syntax-theme-light.css") (prefers-color-scheme: light);


[extra]

# control dark mode: auto | dark | toggle
mode = "toggle"

subtitle = "Linux and Tech related stuff"

# interal CDN resource
useCDN = false

favicon = "/icon/favicon.png"

copyright = "sradjoker"

# ga = "G-6YGDB8SLBT"

# math support
katex_enable = true
katex_auto_render = true

[extra.translations]
languages = [{name = "en", url = "/"}]

[[extra.translations.en]]
show_more = "Read more ⟶"
previous_page = "← Previous"
next_page = "Next →"
posted_on = "on "
posted_by = "Published by"
read_time = "minute read"
all_tags = "All tags"
menus = [
    { name = "Home", url = "/", weight = 2 },
    { name = "All posts", url = "/posts", weight = 2 },
    { name = "Tags", url = "/tags/", weight = 3 },
    { name = "About", url = "/about/", weight = 4 },
    { name = "Now", url = "/now/", weight = 5 },
    { name = "Uses", url = "/uses/", weight = 6 },
]

# config social icon info in the footer
[[extra.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/sravanpannala"

[[extra.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/sradjoker"

# [[extra.social]]
#  icon = "gitlab"
# name = "GitLab"
# url = "https://gitlab.com/sradjoker"

